name: LARC NEWS WATCHER

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install dependencies
        run: pip install requests beautifulsoup4

      - name: run larc watcher
        run: python larc_news_watcher.py
        env:
          LARC_WEBHOOK: ${{ secrets.LARC_WEBHOOK }}

      - name: update seen file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add larc_seen.json

          git diff --cached --quiet || git commit -m "update seen"

          git pull --rebase origin main

          git push

